### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by lgritz** [zpelgrims/pota#10]
There seems to be no license file. What are the licensing terms for this open source project?

**Comment by zpelgrims** [comment]
Hi Larry,

Cool to hear from you, love what you've been pushing in this industry.

I'm not incredibly familiar with the various kind of open-source licenses. Since I only did the Arnold implementation of the paper, I think it would make sense to carry the open-source license of the polynomial optics source code over? I can ask Johannes what this is exactly, as no license file is included there.

Sidenote, I'm looking to move to Vancouver this summer and Sony is high on my list - if you'd be interested in having me, I'd love to talk about it.

**Comment by lgritz** [comment]
The problem is that having no posted license means it's not really open source at all, legally speaking. People will come to the page and then just leave when they realize there's no way for them to figure out what they can or cannot legally do with the code, so it's safest to not look at all.

I recommend either Apache 2.0, that seems to be the favored these days for new open source projects (in our industry, at least), though "new" BSD 3-clause license is also fine.

If you copied part of this code from elsewhere, you may need to adopt its license (depending on what it is -- or at least provide a proper acknowledgement and disclose of its licensing terms and copyright notice as part of yours). If you wrote it all yourself and merely were inspired or based in on reading papers or something, then you can use whichever license you choose.

Feel free to contact me offline about openings we may have. There's usually a mostly up to date listing of current openings on the main imageworks.com web site somewhere.

**Comment by zpelgrims** [comment]
Thanks for that explanation - I learned a few things. I'll make sure the open-source code will actually be open-source in this case.

**Comment by zpelgrims** [comment]
Hi Larry,

Pota now has a MIT license, as that was the license one of the paper's authors suggested. Thanks for pointing this out!
